# about clever cloud
brand: Clever Cloud
since: 2010

# site-wide navigation
nav:
  
  main: [solution, pricing, add-ons, support]
  
  support: [contact-us, partnership]
  
  footer: [clever-cloud, product, support, commitment]
  
  clever-cloud: [about, press-releases, "http://facebook.com/clevercloudsas", "http://twitter.com/clever_cloud"]
  
  product: [solution, pricing, add-ons, signup]
  
  commitment: [legal-notice]

# i18n
locales:
  
  support:
    fr: Support
    en: Support
  
  clever-cloud:
    fr: Clever Cloud
    en: Clever Cloud
  
  product:
    fr: Le produit
    en: Product
  
  commitment:
    fr: Engagements
    en: Our commitment
